app = "vscu-evopay"
primary_region = "ams"

[build]
  command = "java -jar vscu-v2.0.21.jar"

[[services]]
  internal_port = 8090
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
